### ISSUE TITLE
GitLab CE API V3 -> V4

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#110]
https://docs.gitlab.com/ce/api/v3_to_v4.html

**Comment by it-praktyk** [comment]
IMHO, it can be closed now.

BTW, deletion of the APIv3 is scheduled for GitLab 11.0 - the opened GitLab issue: [Removal of API v3 from the codebase](https://gitlab.com/gitlab-org/gitlab-ce/issues/36819)

**Comment by ngetchell** [comment]
I agree with @it-praktyk . Closing now.
