### ISSUE TITLE
add -UserID to New-GitLabUserKey.ps1

### ISSUE THREAD

**Issue by ddobert** [ngetchell/PSGitLab#114]
I'd like to propose a change to PSGitLab/PSGitLab/Public/Keys/New-GitLabUserKey.ps1 because I didn't find a way with PSGitLab to add a ssh key to a different user (I'm an admin).

The GitLab API seems to provide this functionality, see https://docs.gitlab.com/ce/api/users.html#add-ssh-key-for-user 

Could you add a parameter like "-UserID" to the cmdlet to allow adding a ssh key for another user?

**Comment by ngetchell** [comment]
So the proposal would be as follows? 

``` powershell
New-GitLabUserKey -Key <string> [-Title <string>] [-User <string>]

New-GitLabUserKey -KeyFile <string> [-User <string>]
```

**Comment by ddobert** [comment]
Yes, exactly. Thank you!
