### ISSUE TITLE
PSGitLab 2.5.4 from PSGallery contains three different copies of the module

### ISSUE THREAD

**Issue by DHowett** [ngetchell/PSGitLab#122]
```
PS ...\PSGitLab\2.5.4> Get-Content PSGitLab.psm1 |
    Select-String "Function New-GitLabUser {" |
    Measure

Count    : 3
```

The build system will concatenate the module's constituent functions into the `psm1` multiple times on subsequent builds if `Clean` isn't run between them.

**Comment by ngetchell** [comment]
Was able to replicate.
