### ISSUE TITLE
Better on boarding docs

### ISSUE THREAD

**Issue by majkinetor** [ngetchell/PSGitLab#127]
I want to try this out, and provide PRs as I see the missing parts, but it isn't obvious what one should do to setup.

You should update the docs to reflect this, mention Save-GitLabApiConfig and friends and give few quick examples of usage.

**Comment by ngetchell** [comment]
Noted.

As for documentation on usage, I'm thinking an about_PSGitLab as well as a revamped README. Would that suffice?

For the PRs. Should I point to examples of easy functions to steal from as well as how to build and test your new code?

**Comment by majkinetor** [comment]
Yeah, that would suffice. 

I usually generate `about_` file from `README.md` with some lines removed (i.e. build shield etc.).
