### ISSUE TITLE
MacOS Powershell not supported

### ISSUE THREAD

**Issue by planetscripton** [ngetchell/PSGitLab#145]
## 2. Describe Your Environment
Operating System and PowerShell version:
MacOS 10.13.3, PowerShell 6.0.1

## 3. Expected Behavior
[comment] If you're describing a bug, tell us what should happen
[comment] If you're suggesting a change/improvement, tell us how it should work

MacOS should be supported when running Save-GitlabApiConfiguration

## 4.Current Behavior
[comment] If describing a bug, tell us what happens instead of the expected behavior
[comment] If suggesting a change/improvement, explain the difference from current behavior

Currently checks for $IsLinux and $IsWindows, but not $IsMacOS. Gives unknown platform error for MacOS.

## 5. Possible Solution
[comment] Have a solution in mind?

## 6. Context
[Comment] How has this issue affected you? What are you trying to accomplish?
Trying to use PowerShell for MacOS for all my gitlab management.

**Comment by ngetchell** [comment]
I'll have to steal my wife's Macbook Air for the night and see what I can fix.

**Comment by planetscripton** [comment]
Look forward to being able to use this on mac :)
