### ISSUE TITLE
All commands fail with generic error message

### ISSUE THREAD

**Issue by planetscripton** [ngetchell/PSGitLab#146]
## 2. Describe Your Environment
Operating System and PowerShell version:
Windows 10 64Bit, PowerShell 5.1
I have tried with both my personal account/access token, and the root/admin account/access token.
GitLab CE version 10.0.3

## 3. Expected Behavior
[comment] If you're describing a bug, tell us what should happen
[comment] If you're suggesting a change/improvement, tell us how it should work
get-gitlabproject should retrieve list of projects
get-gitlabsetting should retrieve settings
etc.

## 4.Current Behavior
[comment] If describing a bug, tell us what happens instead of the expected behavior
[comment] If suggesting a change/improvement, explain the difference from current behavior

I get the following error to all cmdlets:
WARNING: . See https://gitlab.***.***/help/api/README.md#status-codes for more information.

## 5. Possible Solution
[comment] Have a solution in mind?

## 6. Context
[Comment] How has this issue affected you? What are you trying to accomplish?
Unable to use the module.

**Comment by DHowett** [comment]
I've seen this happen with a self-hosted instance over SSL. Does that match your experience?

If so, try it with Powershell Core (6.0+)

**Comment by ngetchell** [comment]
Hello @planetscripton. Please try running the following code (substitute your information as needed)

``` powershell
Save-GitLabAPIConfiguration -Token 'fdfdf' -Domain 'https://example.com' -APIVersion 3
Test-GitLabAPI
```

**Comment by ngetchell** [comment]
Also @planetscripton what is your SSL configuration? Is it a certificate that is trusted by your computer or is it self-signed?

**Comment by planetscripton** [comment]
The command you listed above does work if I try it with PowerShell Core 6.0.1, instead of Windows PowerShell 5.1.

We are using SSL, it is a certificate signed by Godaddy.

**Comment by planetscripton** [comment]
Sorry, forgot to mention, it is self hosted.

**Comment by ngetchell** [comment]
Very interesting. What error do you get after running Test-GitlabApi on 5.1?

**Comment by planetscripton** [comment]
I get this response:
 Test-GitLabAPI
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At C:\Program Files\WindowsPowerShell\Modules\psgitlab\2.5.9\PSGitLab.psm1:168 char:15
+ ...   $Result = Invoke-WebRequest -UseBasicParsing -Uri "$Domain/api/$Ver ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 

StatusCode StatusText
---------- ----------
         0

**Comment by DHowett** [comment]
This seems to be a `System.Net.Http` issue in .NETFramework, and PowerShell (therefore PSGitlab) is just failing due to that underlying issue:

```
(libra) ~ % Invoke-WebRequest https://gitlab.howett.net/
iwr : The underlying connection was closed: An unexpected error occurred on a send.
```

```
(libra) ~ % $cli = New-Object System.Net.Http.Httpclient
(libra) ~ % $s=$cli.GetAsync([uri]"https://gitlab.howett.net/")
(libra) ~ % $s
(libra) ~ % $s.Exception
One or more errors occurred.
(libra) ~ % $s.Exception.InnerException
An error occurred while sending the request.
```

**Comment by DHowett** [comment]
```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error
occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An
unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection:
An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing
connection was forcibly closed by the remote host
```

**Comment by DHowett** [comment]
Sorry for the spam. This is because gitlab's default configuration rejects TLS < 1.2.

This completely fixes the issue (at all levels: PSGitLab, Powershell and System.Net.Http) for me:
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

but it is unfortunately session-global and not request-specific.

**Comment by planetscripton** [comment]
Makes sense - that fixed it for me. Thanks!

**Comment by ngetchell** [comment]
@DHowett  Thanks for beating me too this issue. Great detective work. 

@planetscripton  Let me know if there are any other issues!
