### ISSUE TITLE
SecureString Type Conversion Error Out Of The Box On Linux

### ISSUE THREAD

**Issue by raisin-loaf** [ngetchell/PSGitLab#150]
## Describe Your Environment
CentOS 7.4.1708 - PowerShell Core 6.0.2

## Expected Behavior
To run `Test-GitLabAPI` and have it complete successfully

## Current Behavior
Out of the box `Test-GitLabAPI` errors with a type conversion (cannot convert `System.String` to `System.Security.SecureString`) relating to the `DecryptString` function when reading the API key from the saved information.

## Possible Solution
I can get it to work (and by extension the entire module) through editing the `DecryptString` function, changing the parameter type to `[String]` and commenting out 99% of the function so all it does is return the incoming parameter:

```powershell
function DecryptString {
param(
    [Parameter(ValueFromPipeline=$true,Mandatory=$true,Position=0)]
    [String]
    $Token
)

# $marshal = [System.Runtime.InteropServices.Marshal]
# $ptr = $marshal::SecureStringToBSTR( $token )
# $key = $marshal::PtrToStringBSTR( $ptr )
# $marshal::ZeroFreeBSTR( $ptr )
# $key
# Remove-Variable key

$Token
}
```

It's funny cause when you run `Save-GitLabAPIConfiguration` you get a warning that 'Your GitLab token will be stored in plain-text on non-Windows platforms' which sets the expectation that it'll be read in plain text.

**Comment by ngetchell** [comment]
Was able to reproduce on Ubuntu. DecryptString shouldn't run on Linux. All of the functions use the QueryGitLabAPI which bypasses DecryptString on Linux. 

The only function to bypass QueryGitLabAPI is ....... Test-GitLabAPI. Expect a new version soon.
