### ISSUE TITLE
New-GitLabProjet fails with "cannot call a method on a null-value expression"

### ISSUE THREAD

**Issue by NealWalters** [ngetchell/PSGitLab#177]
## 1. Provide a general summary of the issue in the Title above
Trying first time to create new empty project: 
New-GitlabProject  -name "Neal.Test.GitLab.NewProject1" -path "AAA.BBB" -description "Test Gitlab Script"

## 2. Describe Your Environment
Operating System and PowerShell version:
Win2012/R2, PS 5.1.14409.1005, 
Re-installed PSGitLab today 

## 3. Expected Behavior
Project should be created or give a more friendly error.  It's giving me errors on line numbers in your code.

## 4.Current Behavior
```
You cannot call a method on a null-valued expression.
At C:\Program Files (x86)\WindowsPowerShell\Modules\GitLab-API\obj\gitlabconnect.ps1:88 char:5
+     $header = @{
+     ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files (x86)\WindowsPowerShell\Modules\GitLab-API\New-GitLabProject.ps1:232 char:5
+     $newproj = $GitlabConnect.callapi($apiurl,$httpmethod,$parameters ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

## 5. Possible Solution
I'm not exactly sure what a -path or -namespace is in GitLab.  I put in the Group Name. 

## 6. Context
This is my first step in trying to create a new project, then a personal branch, then our standard branch called "develop" before checking in code. 

##7 . Questions
1) Will it return the Project ID after creating it?  If not, how do I lookup the project id to use in my next step, which will be New-GitLabProjectBranch? 
2) Do all the -isXxxx options default to $true or $false?

**Comment by NealWalters** [comment]
Similar is happening on other commands (such as Get-GitLabProject with no parms).  I thought I verified things working this morning when I closed my previous issue (https://github.com/ngetchell/PSGitLab/issues/174).  Then this afternoon, had time to attempt what I really wanted to do.  I tried both http and https. 

Before that command, I have: 
Save-GitLabAPIConfiguration -Token 'whatever' -Domain 'https://git.mysite.com' -APIVersion 3

**Comment by ngetchell** [comment]
There is something wrong with the path parameter. Looking into it now.

**Comment by NealWalters** [comment]
What exactly is Path?  I probably don't the GitHub/GitLab terminology well enough. 
When using GitLab, my projects are under for example: MyCompany.ABC,  I think that's called a Group.  Is that the same as Path? 

If Path is bad or wrong, please just send back an error that makes sense. 

Thanks
Neal

**Comment by AkhilaDamera** [comment]
is there a solution for this bug?? I am facing similar error while creating a project with New-GitLabProject 
Appreciate your response.

Thanks,
Akhila

**Comment by demeesterdev** [comment]
@NealWalters @AkhilaDamera 
could you check the module you installed?
looking at the error you installed the gitlab api module I previously created.
https://www.powershellgallery.com/packages/GitLab-API

I have deprecated it since I first created it because I found out that @ngetchell is a lot more active on maintaining its implementation.

removing the module `Gitlab-API` and installing PSGitLab should resolve your issue.

**Comment by ngetchell** [comment]
How did I miss that! 

Thanks @tdemeester.

**Comment by ngetchell** [comment]
@AkhilaDamera Please open a new issue if your still having a problem. 

This specific issue is closed but you likely have a different problem.

**Comment by NealWalters** [comment]
Sorry for the absence.  Are you saying that PSGitLab should be used instead of GitLabProject?  Or pick and choose best modules from each? 

Thanks,
Neal

**Comment by NealWalters** [comment]
Sorry for my absence.  It's been low priority to get Poweshell working with GitLab here. 

Installed the latest, and ran this after doing my Save-GitLabAPIConfiguration: 

PS BizTalk:\Applications> Get-GitLabProject -Search "MyCompany.MyProject" 
WARNING: . See https://git.echo.com/help/api/README.md#status-codes for more information.

What is expected to happen?  I should see some data about the project, right? 
What happened: Got the cryptic warning above. 

Now we are back to my other unsolved issue: 
https://github.com/ngetchell/PSGitLab/issues/174

Thanks,
Neal
