### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#178]
I tried to be slick by reporting any non 200 HTTP codes as gitlab errors. This covers up so many PSGitlab errors that I think it should be scrapped or at least redesigned.

**Comment by it-praktyk** [comment]
I've observed that GitLab returns errors like
```json
{
    "message": "401 Unauthorized"
}
```

**Comment by ngetchell** [comment]
I was poking around the exception object with Show-Object and found that the web cmdlets have error messages from the API in them, not just HTTP codes. You can find the commit here, https://github.com/ngetchell/PSGitLab/commit/13aeab83f496b33c94deb5647a52065181d7eae3 .
