### ISSUE TITLE
Get-GitlabProject no longer returns projects.

### ISSUE THREAD

**Issue by robinmalik** [ngetchell/PSGitLab#196]
Upgraded from commit 2729d09 to commit 89a5252. `Get-GitlabProject` returns nothing by default now. `Get-GitlabProject -All` returns an error.

## 2. Describe Your Environment
Windows 10 x64 Enterprise Build 1809 Build 17763.1
PSVersion 5.1.17763.1

## 3. Expected Behavior
Projects returned.

## 4.Current Behavior

```
Get-GitLabProject -Verbose
VERBOSE: Create GET Request
VERBOSE: Parameter Set Name: Projects
VERBOSE: URL: https://domain.com/api/v4/projects?archived=false&order_by=created_at&sort=desc&per_page=100
VERBOSE: GET https://domain.com/api/v4/projects?archived=false&order_by=created_at&sort=desc&per_page=100 with 0-byte payload
VERBOSE: received 83047-byte response of content type application/json
```
and
```
Get-GitLabProject -All
QueryGitLabAPI :
At C:\Users\Robin\Documents\Repositories\PSGitLab\PSGitLab\Public\Projects\Get-GitLabProject.ps1:155 char:5
+     QueryGitLabAPI -Request $Request -ObjectType 'GitLab.Project'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,QueryGitLabAPI
```

## 5. Possible Solution
The problem seems to have been introduced with the 'archived' parameter. This example from a previous version returns results (and doesn't contain archived=false in the URL):

```
Get-GitLabProject -Verbose
VERBOSE: Create GET Request
VERBOSE: Parameter Set Name: Projects
VERBOSE: URL: https://domain.com/api/v4/projects?order_by=created_at&sort=desc&per_page=100
VERBOSE: GET https://domain.com/api/v4/projects?order_by=created_at&sort=desc&per_page=100 with 0-byte payload
VERBOSE: received 83047-byte response of content type application/json
```

**Comment by robinmalik** [comment]
This is odd. Both the following URLs work in a browser:
```
https://domain.com/api/v4/projects?order_by=created_at&sort=desc&per_page=100
https://domain.com/api/v4/projects?archived=false&order_by=created_at&sort=desc&per_page=100
```
but only the first one works when using PowerShell.

I have however confirmed that git reset --hard 5fb4549d6d9716819d1783659b7ce4f07d19d617 results in `Get-GitlabProject` returning project results (but `Get-GitlabProject -All` still returns and error).

**Comment by Plork** [comment]
looks related to this:

https://github.com/ngetchell/PSGitLab/pull/195#discussion_r221895364

**Comment by ngetchell** [comment]
Fixed by https://github.com/ngetchell/PSGitLab/pull/197
