### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by jetersen** [ngetchell/PSGitLab#207]
## 1. Provide a general summary of the issue in the Title above

Looking through the project, I see the inconsistency in the code style, I would have a hard time contributing without agreeing on a code style.

No indents: https://github.com/ngetchell/PSGitLab/blob/master/PSGitLab/Private/DecryptString.ps1
2 Space indents with varied spacing too: https://github.com/ngetchell/PSGitLab/blob/master/PSGitLab/Private/DownloadFromGitLabAPI.ps1
4 space idents: https://github.com/ngetchell/PSGitLab/blob/master/PSGitLab/Private/FormatCommits.ps1

So what is? Would love to add an `.editorconfig` and some PR quality checks.

**Comment by ngetchell** [comment]
Sorry that the lack of consistency is keeping you from contributing. My goal is to make the barrier to entry small so more of the GitLab API is covered by more people. I don't have the time to produce all of the code in the module so it requires help. More hands means more inconsistency. 

In this case, I'd welcome help with setting a standard and using technology to guide contributors as long as they are guidelines. Tests and Linting via PSScriptAnalyzer are as far as I'd like the project to go when it comes to requirements before merging. 

I look forward to viewing your PR!

**Comment by robinmalik** [comment]
Interesting view. It makes sense to keep the barrier for entry low; this is one of the great things about PowerShell.

Personally the imposition of strict rules off-putting and is likely to result in me not engaging, unless there is **extremely clear** documentation on how to automatically format code after writing in our own style.

**Comment by jetersen** [comment]
@robinmalik the formatting is pretty clear in that VSCode will format as expected since it is setup inside the branch of #208 and CI will complain if you skipped on formatting.

If you're using a different editor, I suggest you configure it once and commit it to the repo.  
If you're using PowerShell ISE your out of luck 😆

**Comment by robinmalik** [comment]
Ok, if it's automated via CI then that's great! (also: VSCode ftw).

**Comment by jetersen** [comment]
I agree. Humans should not care about formatting unless it prevents the readability.  
Which in this case it does.  
I had a tough time contributing to project without the changes looking like major refactoring because the code format made it hard to read and the code that had changed looked like gratuitous changes.

**Comment by ngetchell** [comment]
Thanks for tackling it @casz. I go back and forth on mandating readability but I feel like I chose incorrectly years ago and now have to pay the price.
