### ISSUE TITLE
PlatyPS Documentation

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#46]
Convert to https://github.com/PowerShell/platyPS help instead of just MAML or comment-based help. This should enhance what help looks like at the console and should allow for better collaboration with the community. 

@it-praktyk

**Comment by it-praktyk** [comment]
Mardown documentation can be generated from the help based help. In the next step markdown files can be converted to MAML :-)

**Comment by ngetchell** [comment]
#91 merged.
