### ISSUE TITLE
Merge functions into .psm1

### ISSUE THREAD

**Issue by McAndersDK** [ngetchell/PSGitLab#48]
###### 
# Build Script
###### 

$RootPath = get-item $psscriptroot
$ModuleName = ($rootPath.BaseName -split "-")[1]
$ModulePath = "$psscriptroot/$ModuleName"
$release = "$psscriptroot/Release/$ModuleName"
$PublicFunctions = @()
$AliasToExports = @()
$FileList = @()
$manifest = "$release\$modulename.psd1"
if(test-path $release) {
    Remove-Item -Recurse -Force -Confirm:$false -Path $release
}
new-item $release -Force -ItemType directory

copy-item "$ModulePath\$modulename.psd1" $manifest -Force
$FileList += "$modulename.psd1"
$FileList += "$modulename.psm1"

"########################" | Add-Content "$release\$ModuleName.psm1"
"### Public Functions ###" | Add-Content "$release\$ModuleName.psm1"
"########################" | Add-Content "$release\$ModuleName.psm1"
foreach($function in (get-childitem $ModulePath\Public\ -Recurse)) {
    $PublicFunctions += $function.basename
    $content = Get-Content $function.fullname 
    $content | Add-Content "$release\$ModuleName.psm1"
    if($content -match '[Alias(([^)]*)') {
        foreach($alias in ($matches[1] -split ",") -replace ("`"",''))  {
            $AliasToExports += $alias
        }
    }
}
"#########################" | Add-Content "$release\$ModuleName.psm1"
"### Private Functions ###" | Add-Content "$release\$ModuleName.psm1"
"#########################" | Add-Content "$release\$ModuleName.psm1"
foreach($function in (get-childitem $ModulePath\Private\ -Recurse)) {
    Get-Content $function.fullname | Add-Content "$release\$ModuleName.psm1"
}

Update-ModuleManifest -Path $manifest -FunctionsToExport $PublicFunctions -AliasesToExport $AliasToExports -FileList $FileList

**Comment by ngetchell** [comment]
I have seen recommendations for including FunctionsToExport in your manifest to speed up with Import-Module process. Would speed also be the reason for merging the PSM1 file? I will check the Import times for a combined PSM1 vs my current setup. 

If I missed a reason please let me know. 

@McAndersDK do you think this would fit into a Psake build task? My goal would be to keep development easy for people to contribute and I believe separate PS1 files does that best (merging, diffing, etc). 

I don't have access to Update-ModuleManifest yet as I am running PS5 RTM and I 'build' from that . Will look into this as soon as I get the next Win 10 build. 
- [x] Check if combined PSM1 is faster for importing module.
- [x] Check if combined PSM1 is faster for intellisense from the console. 
- [ ] Investigate Update-ModuleManifest for dynamically updating manifest information.

**Comment by michaeltlombardi** [comment]
Speed is one reason to condense, the other is simplicity for users - they only have to review one file for code. The majority of users are not power users and are not using tools with multi-file search-and-edit.

Not sure if it's faster for intellisense, but my tests were faster for import.

FWIW, in my projects for work we condense from multiple files into a single psm1 - our deployed module only has the following in the structure:

```
ModuleName
├── ModuleName.psd1
└── ModuleName.psm1
```

If you have formatting/etc, you can deploy with those files too - the point is to reduce cognitive load for average users. We don't include tests either.

**Comment by ngetchell** [comment]
I'll look into this today. @michaeltlombardi do you run your pester tests against your multiple file folder or your condensed PSM1?

**Comment by michaeltlombardi** [comment]
I run pester tests against the pre-compiled version. The compiled/condensed psm1 _only_ exists as an artifact **if** all tests pass before it.

For non-master branches:
`Push to remote -> automatic tests -> report`

For master:
`Merge to master -> automatic tests -> if successful, build module -> if successful, deploy module`
