### ISSUE TITLE
Better Build Process

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#58]
A consistent build process is something I should look into. Should do the following.
- [ ] Invoke-Pester
- [ ] Invoke-ScriptAnalyzer
- [ ] Generate MAML help from markdown files #46 
- [ ] Update Module Version Number
- [ ] Update FunctionsToExport
- [ ] #48 
- [ ] Push to the PSGallery under certain conditions

**Comment by ngetchell** [comment]
I've used PSake before and will see about using it now.

**Comment by michaeltlombardi** [comment]
Psake is definitely the right way to go with this.  Might want to look at something like @devblackops's work on [POSHOrigin](https://github.com/devblackops/POSHOrigin/) for the [psake](https://github.com/devblackops/POSHOrigin/blob/master/psake.ps1) and [build](https://github.com/devblackops/POSHOrigin/blob/master/build.ps1) files.
