### ISSUE TITLE
Remove-GitLabProject Support Pipeline

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#60]
Remove-GitLabProject says it supports pipeline parameters but only removes the first one you give it. This has to be fixed. 

https://github.com/ngetchell/PSGitLab/blame/master/PSGitLab/Public/Projects/Remove-GitLabProject.ps1#L18-L29

**Comment by michaeltlombardi** [comment]
Should this issue have been closed by #61?

**Comment by ngetchell** [comment]
Correct. Confirmed that this is no longer working on 2.3.1.
