### ISSUE TITLE
Help Pester Tests

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#66]
After we complete #46 we should look into better pester tests around help. An example would be June Blender's PesterTDD [Module Help](https://github.com/juneb/PesterTDD/blob/master/Module.Help.Tests.ps1).

**Comment by ngetchell** [comment]
I've got this almost complete. I just want to get parameter checking up and running and this will be resolved.

**Comment by it-praktyk** [comment]
You can be interested in pester/Pester/pull/652 .

**Comment by ngetchell** [comment]
Thanks @it-praktyk. Is there any reason to use the AST over Get-Command to tell what parameters are included in a function?

**Comment by ngetchell** [comment]
Tracking this on parameterHelp branch,
