### ISSUE TITLE
Author Attribution

### ISSUE THREAD

**Issue by ngetchell** [ngetchell/PSGitLab#82]
Right now my name is the only name on PSGitLab but I'd like to add others. I'd like to add the contributor's names to the following places: 

- [ ] README
- [ ] Module Manifest
- [ ] PSGallery

Let me know if you want your name added or just your GitHub handle. If you have any personal sites you'd like to have added I think the README would be a perfect place for it. 

@TerrapinStation 
@lw-schick

**Comment by lw-schick** [comment]
My full name is Leonhard Schick. I have still no personal active website. I will inform you when I have one...

**Comment by TerrapinStation** [comment]
Hey Nicholas,

Either name (Brooks Collins )or GitHub handle works. Whatever best matches the format for the other contributers

Thanks,

Brooks
